# VM Configuration file for Performance Benchmark Suite
# vm_config.yaml

# VM size configurations
vm_configs:
  small:
    vcpus: 2
    memory_mb: 2048      # 2GB RAM
    disk_size_gb: 20
    description: "Basic VM for lightweight workloads"

  medium:
    vcpus: 4
    memory_mb: 4096      # 4GB RAM
    disk_size_gb: 40
    description: "Standard VM for general workloads"

  large:
    vcpus: 8
    memory_mb: 8192      # 8GB RAM
    disk_size_gb: 80
    description: "High-performance VM for intensive workloads"

# Network configuration
network:
  type: bridge
  bridge_name: virbr0    # Default libvirt bridge
  model: virtio          # Network adapter model
  mac_prefix: "52:54:00" # Default QEMU MAC prefix

# Storage configuration
storage:
  pool_name: default
  pool_path: /var/lib/libvirt/images
  disk_format: qcow2
  disk_bus: virtio
  io_mode: native
  cache_mode: none       # Direct I/O for better performance measurement

# VM base image
image:
  name: ubuntu-22.04-server
  format: qcow2
  url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img

# Additional VM settings
settings:
  cpu_mode: host-passthrough  # Better performance by exposing host CPU features
  memory_backend: hugepages   # Use hugepages for better memory performance
  numa_enabled: true          # Enable NUMA support if available
  cpu_pinning: false         # CPU pinning can be enabled for better performance
  
# Resource limits
limits:
  cpu_shares: 1024
  cpu_period: 100000
  cpu_quota: -1              # -1 means no quota
  memory_swappiness: 0       # Disable swapping for better performance
  
# Performance tuning
tuning:
  disk_io:
    aio: native
    iothread: true
  network:
    txqueuelen: 1000
    gso: on
    tso: on
    gro: on
